<?xml version='1.0'?>
<robot name="my_fbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find my_fbot)/urdf/my_fbot.gazebo"/>

    <!--    VARIABLES-->
    <xacro:property name="chassis_height" value=".1"/>
    <xacro:property name="chassis_radius" value=".1"/>
    <xacro:property name="sup_wheels_height" value="-0.0249"/>


    <xacro:property name="wheel_thickness" value=".025"/>
    <xacro:property name="wheel_radius" value=".05"/>

    <!--    MATERIALS-->
    <gazebo reference="chassis">
        <material>Gazebo/Grey</material>
    </gazebo>

    <gazebo reference="left_wheel">
        <material>Gazebo/Red</material>
    </gazebo>

    <gazebo reference="right_wheel">
        <material>Gazebo/Red</material>
    </gazebo>

    <!--link to ground-->
    <link name="robot_footprint"/>

    <joint name="robot_footprint_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="robot_footprint"/>
        <child link="chassis"/>
    </joint>

    <!--    chassis link-->
    <link name='chassis'>
        <pose>0 0 0 0 0 0</pose>

        <inertial>
            <mass value="15.0"/>
            <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
            <inertia
                    ixx="0.1" ixy="0" ixz="0"
                    iyy="0.1" iyz="0"
                    izz="0.1"
            />
        </inertial>

        <collision name='collision'>
            <origin xyz="0 0 ${wheel_radius/2}" rpy=" 0 0 0"/>
            <geometry>
                <cylinder length="${chassis_height}" radius="${chassis_radius}"/>
            </geometry>
        </collision>

        <visual name='chassis_visual'>
            <origin xyz="0 0 ${wheel_radius/2}" rpy=" 0 0 0"/>
            <geometry>
                <cylinder length="${chassis_height}" radius="${chassis_radius}"/>
            </geometry>
        </visual>

        <!--        SUPPORT WHEELS-->
        <collision name='back_caster_collision'>
            <origin xyz="-${chassis_radius/3} 0 ${sup_wheels_height}" rpy=" 0 0 0"/>
            <geometry>
                <sphere radius="${wheel_radius/2}"/>
            </geometry>
        </collision>

        <visual name='back_caster_visual'>
            <origin xyz="-${chassis_radius/3} 0 ${sup_wheels_height}" rpy=" 0 0 0"/>
            <geometry>
                <sphere radius="${wheel_radius/2}"/>
            </geometry>
        </visual>

        <collision name='front_caster_collision'>
            <origin xyz="${chassis_radius/3} 0 ${sup_wheels_height}" rpy=" 0 0 0"/>
            <geometry>
                <sphere radius="${wheel_radius/2}"/>
            </geometry>
        </collision>

        <visual name='front_caster_visual'>
            <origin xyz="${chassis_radius/3} 0 ${sup_wheels_height}" rpy=" 0 0 0"/>
            <geometry>
                <sphere radius="${wheel_radius/2}"/>
            </geometry>
        </visual>

        <!--        LIDAR SUPPORT-->
        <collision name='lidar_support_collision'>
            <origin xyz="-0.05 0 ${chassis_height-0.02}" rpy=" 0 0 0"/>
            <geometry>
                <cylinder length="0.05" radius="0.1"/>
            </geometry>
        </collision>

        <visual name='lidar_support_visual'>
            <origin xyz="-0.05 0 ${chassis_height-0.02}" rpy=" 0 0 0"/>
            <geometry>
                <cylinder length="0.02" radius="0.05"/>
            </geometry>
        </visual>

    </link>

    <!--    WHEELS LINKS-->
    <link name="left_wheel">
        <inertial>
            <mass value="5"/>
            <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
            <inertia
                    ixx="0.1" ixy="0.0" ixz="0.0"
                    iyy="0.1" iyz="0.0"
                    izz="0.1"
            />
        </inertial>

        <collision>
            <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </visual>
    </link>

    <link name="right_wheel">
        <inertial>
            <mass value="5"/>
            <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
            <inertia
                    ixx="0.1" ixy="0.0" ixz="0.0"
                    iyy="0.1" iyz="0.0"
                    izz="0.1"
            />
        </inertial>

        <collision>
            <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </visual>
    </link>

    <!--    CAMERA-->
    <link name="camera">
        <inertial>
            <mass value="0.1"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.03" ixy="0.0" ixz="0.0" iyy="0.03" iyz="0.0" izz="0.03"/>
        </inertial>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="0.02"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://computer_vision_pkg/meshes/head.dae" scale=".5 .5 .5"/>
            </geometry>
        </visual>
    </link>

    <!--    LIDAR-->
    <link name="hokuyo">
        <inertial>
            <mass value="1e-5"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia
                    ixx="1e-6" ixy="0.0" ixz="0.0"
                    iyy="1e-6" iyz="0.0"
                    izz="1e-6"
            />
        </inertial>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://my_fbot/meshes/hokuyo.dae"/>
            </geometry>
        </visual>
    </link>

    <!--    JOINTS-->
    <joint type="continuous" name="left_wheel_hinge">
        <origin xyz="0 ${chassis_radius} 0" rpy="0 0 0"/>
        <parent link="chassis"/>
        <child link="left_wheel"/>
        <axis xyz="0 1 0" rpy="0 0 0"/>
        <limit effort="10000" velocity="1000"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <joint type="continuous" name="right_wheel_hinge">
        <origin xyz="0 -${chassis_radius} 0" rpy="0 0 0"/>
        <parent link="chassis"/>
        <child link="right_wheel"/>
        <axis xyz="0 1 0" rpy="0 0 0"/>
        <limit effort="10000" velocity="1000"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <joint name="camera_joint" type="continuous">
        <axis xyz="0 1 1"/>
        <origin xyz="0.09 0 ${chassis_height-0.1}" rpy="0 0 0"/>
        <parent link="chassis"/>
        <child link="camera"/>
    </joint>

        <transmission name="camera_transmission">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="$camera_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="camera_joint">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
        </transmission>

    <joint name="hokuyo_joint" type="fixed">
        <origin xyz="-0.05 0 ${chassis_height+0.02}" rpy="0 0 0"/>
        <parent link="chassis"/>
        <child link="hokuyo"/>
        <axis xyz="0 1 0"/>
    </joint>

</robot>